sudo: required

language: python

python:
  - "3.6"

cache:
  - pip

before_script:
  - sudo pip install pelican mistune pillow
  - git clone --depth=1 https://github.com/PoiScript/Solomon-Post.git content

script:
  - make html

after_success:
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change